### ISSUE TITLE
Contest Time

### ISSUE THREAD

**Issue by asharimh97** [StudyIntraScientica/regrader#3]
Jadi saya nemuin masalah ketika kita bikin sebuah kontes di hari yang sama dengan sekarang. Kalau misalnya tanggalnya dimundurkan 1 hari saja kontes akan muncul status running, tapi ketika tanggalnya sama di dasbor tidak ada running contest. How?

**Comment by harunakaze** [comment]
@asharimh97 ini tadi yang sebelum kamu nemunin masalah di GMT time-nya atau udah dibenerin yak?

**Comment by asharimh97** [comment]
Ohiya mas, udah kok. Solved. Hehehe

**Comment by harunakaze** [comment]
Sip tak close issuenya :+1:
